### ISSUE TITLE
hostname doesn't seem to work

### ISSUE THREAD

**Issue by hmook** [AlexanderBabel/homebridge-sonoff#3]
Hi,

If I use the hostname instead of the IP address of my Sonoff the plugin doesn't seem to work anymore. IS this a known issue?

BR, Hanno

**Comment by AlexanderBabel** [comment]
Hey,

it can only find your device if the hostname is known to the device where your homebridge instance is running. Normally the IP-Address of your son off shouldn't change. Therefore you can use the IP instead of the hostname without any issues.

Greetings
Alex

**Comment by hmook** [comment]
Hi @AlexanderBabel and Thanks! Another question is it possible to change the type (now Outlet) to a lightbulb for example?

**Comment by AlexanderBabel** [comment]
I think you can do that in the Home App on your iOS device. Just tap on the settings of the outlet and there you will see a type section. Click on the type and you can choose a different type for your device.

**Comment by hmook** [comment]
Thanks again!
