### ISSUE TITLE
2nd son off device

### ISSUE THREAD

**Issue by boysim** [AlexanderBabel/homebridge-sonoff#7]
how do you add a second sonoff device?

**Comment by Hoefnix** [comment]
could you be a little more specific? you mean a second in your homebridge config then it is like this

{
  "platform": "Sonoff",
  "name": "Sonoff",
  "devices": [
    {
      "name": "Name of the accessory",
      "hostname": "The hostname or local ip address of the 1st Sonoff device",
      "password": "The password from the web interface"
    },
    {
      "name": "Name of the accessory",
      "hostname": "The hostname or local ip address of the 2nd Sonoff device",
      "password": "The password from the web interface"
    }
  ]
}

**Comment by boysim** [comment]
thx that did the trick!
